# Generated by Django 5.0.1 on 2024-02-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('save_path', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('visible', models.BooleanField(default=True)),
                ('author', models.CharField(max_length=500)),
                ('publish_time', models.DateTimeField(verbose_name='essay published')),
                ('last_update_time', models.DateTimeField(verbose_name='essay update')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('user_password_salt', models.CharField(max_length=256)),
            ],
        ),
    ]
