# Generated by Django 5.0.1 on 2024-02-04 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('corpus', '0002_remove_user_user_password_salt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.user'),
        ),
    ]
