# Generated by Django 5.0.1 on 2024-02-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('corpus', '0004_corpus_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='author',
            field=models.CharField(max_length=500),
        ),
    ]
