# Generated by Django 5.0.1 on 2024-02-08 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_series_alter_corpus_publish_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('theme_name', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Series',
        ),
        migrations.AlterField(
            model_name='corpus',
            name='save_path',
            field=models.FilePathField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='corpus',
            name='theme_name',
            field=models.ForeignKey(default='Error', on_delete=django.db.models.deletion.CASCADE, to='corpus.theme'),
            preserve_default=False,
        ),
    ]
