# Generated by Django 5.0.1 on 2024-02-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_theme_delete_series_alter_corpus_save_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='theme_name',
            field=models.CharField(max_length=500),
        ),
    ]
